### ISSUE TITLE
Thanks for doing this.

### ISSUE THREAD

**Issue by cbrew** [dhgutteridge/Brew-Distance#1]
This is nicer code than my original Python, which was written a long time ago, and has 
taken on a life of its own through the Perl module. I need to make clear that I certainly don't think
I deserve named credit. The algorithm is much older than my version, and there are tons of really clever enhancements that you can read about at [https://en.wikipedia.org/wiki/Edit_distance].

**Comment by dhgutteridge** [comment]
I've added a reference to the Wikipedia article you mentioned; since I imagine this project is most likely to be used for educational purposes, it's good to note, thanks. By the way, I found more than one link that referenced your original article, but they're broken now.

I can certainly rephrase the reference to you, if you prefer, but to me, you deserve credit at minimum for spurring the creation of the Perl module, which was a big help to me years back. To myself and others, it's the "Brew distance algorithm". I'd prefer to call it that so this project's relation to the Perl module is clear, too. :)

**Comment by cbrew** [comment]
Yes, the original link is gone because OSU changed their web policies. But this archive caught the original before it went away, so the material is still accessible 17 years later.

http://archive.is/20140611111436/www.ling.ohio-state.edu//~cbrew/795M/string-distance.html

**Comment by dhgutteridge** [comment]
Is there anything more you'd like me to address with the documentation?

**Comment by cbrew** [comment]
Nope. All good. Thanks

**Comment by dhgutteridge** [comment]
Thanks again for your feedback, and the original inspiration for this!
