### ISSUE TITLE
This algorithm is not due to Chris Brew.

### ISSUE THREAD

**Issue by rljacobson** [dhgutteridge/Brew-Distance#3]
It appears that the "Brew distance" computed by your algorithm is nothing more than the Levenshtein edit distance, and the algorithm itself is the well-known Wagner-Fischer algorithm. Chris Brew is not the author of the original algorithm and would prefer to not have his name inappropriately associated with it. The algorithm has apparently been discovered and rediscovered multiple times independently: https://en.wikipedia.org/wiki/Wagner%E2%80%93Fischer_algorithm#History.

I recommend the name of the library be changed and that the phrase "Brew distance" and attribution to Chris Brew be removed.

**Comment by dhgutteridge** [comment]
I think you're putting it a bit too strongly when you say "inappropriately associated to it". It's true he said he didn't think he "deserved named credit" in issue #1. There's a distinction, because he wrote a paper with a specific implementation that then inspired other people to use the same, and I in turn used the Perl implementation, from which I kept the name as a reference (which I believe I make clear in the documentation, and in my response in issue #1).

Having said that, I'm not opposed to changing the name. What would you suggest, "Weighted Edit Distance"? (I would also be curious to see what the response of the Perl module maintainer is here.)

**Comment by rljacobson** [comment]
I do not think I am putting it strongly enough. To be very clear: **_Nothing_** in Chris Brew's "paper" (which was a web page meant only for students in his class) was discovered or invented by Chris Brew. The same is true of the perl module.  I am happy to cite the literature if you feel it necessary. Your readme states: "Chris Brew, the creator of the algorithm." This is _factually incorrect_.

But I also want to be clear that I am not trying to be unnecessarily combative, and I know it's easy to accidentally communicate animus when none is intended when writing text over the internet. Chris certainly DOES deserve credit for being an excellent educator about this algorithm. I just feel it is important that the historical provenance of these ideas are preserved, particularly within the context of academia. 

Since I am the one raising the issue, would you mind if I took a stab at making some minimal edits to resolve what I think is the issue and submit a pull request? Then whenever you have time to review the pull request we can go from there?

Cheers!

**Comment by dhgutteridge** [comment]
I appreciate your concern here, and I'm not trying to be difficult, either. (At the time I created this implementation, I was going off what was stated in the Perl module, and indeed, the link I found to the original article/posting was broken. But, frankly, I wouldn't have been following it back further than that reference.)

From the original issue Chris Brew opened here, I didn't realize this was that sensitive a subject. I'd taken that he was being modest. Especially since my notion for this implementation was that it could be used for educational purposes (no one would use it for speed), we definitely need to fix this.

I've made some edits to the readme file already. I'm certainly open to accepting more if you feel those aren't enough. Renaming the project itself is also a possibility, but that is something I'd want to think about.

**Comment by rljacobson** [comment]
Chris _is_ quite modest, I think, and he's a great researcher and clearly a great expositor of technical material. I have a lot of respect for him.

I made a pull request with a couple of minor edits. I don't see any issue with the project name. Thanks!

Nicely packaged module as well. Thanks for your work on it.

**Comment by dhgutteridge** [comment]
Thanks for catching those, I've merged them.
